[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
serde_json = "1.0.127"
anyhow = "1.0.86"
serde = { version = "1.0.209", features = ["derive"] }
